__all__ = [
    'ambito' 
    , 'db'
    , 'departamento'
    , 'escuela'
    , 'localidad'
    , 'niveleducacion'
    , 'provincia'
    , 'sector'
    , 'tipoeducacion'
    , 'tiponiveleducacion'
    , 'version'
    , 'tables'
    , 'views'
    , 'columns'
    , 'util'
    , 'sesiones'
    , 'config'
]